language: c
os: linux
install:
 - INSTALL_HERE=$(pwd)/libs
 - LIBRARY_PATH=$INSTALL_HERE/lib
 - CPATH="$INSTALL_HERE/include"
 - source .travis/install_cmocka.sh
 - source .travis/install_libft.sh
# - echo "installed :"
# - ls -R $INSTALL_HERE
 - export CPATH
 - export LIBRARY_PATH
 - export LD_LIBRARY_PATH=$LIBRARY_PATH
script:
 - make -k #-p
 - make -k unit-tests
