language: c
os:
 - linux
 - osx
addons:
 apt:
  packages:
   - libbsd-dev
install:
 - INSTALL_HERE=$(pwd)/libs
 - LIBRARY_PATH=$INSTALL_HERE/lib
 - CPATH="$INSTALL_HERE/include"
 - source .travis/install_cmocka.sh
 - source .travis/install_libft.sh
 - export CPATH
 - export LIBRARY_PATH
 - export LD_LIBRARY_PATH=$LIBRARY_PATH
 - source .travis/install_42filechecker.sh
script:
 - make -k #-p
 - make -k unit-tests
 - make clean_fillit && make -C clean_fillit/
 - ~/42FileChecker/42FileChecker.sh 
   --project "fillit" 
   --path "$(pwd)/clean_fillit"
   --no-norminette; cat ~/42FileChecker/.my*
