language: c
os:
 - linux
addons:
 apt:
  packages:
   - libbsd-dev
install:
 - INSTALL_HERE=$(pwd)/libs
 - source .travis/install_cmocka.sh
 - export LD_LIBRARY_PATH=$LIBRARY_PATH
 - source .travis/install_fillit_checker.sh
 - make -C libs/ libft
script:
 - make -k #-p
 - make -k unit-tests
 - make clean_fillit && make -C clean_fillit/
 - cd clean_fillit/ && bash ~/fillit_checker/test.sh .
